// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNames() {
  return window['go']['main']['App']['GetNames']();
}

export function Load() {
  return window['go']['main']['App']['Load']();
}

export function Medications(arg1) {
  return window['go']['main']['App']['Medications'](arg1);
}

export function Save(arg1, arg2) {
  return window['go']['main']['App']['Save'](arg1, arg2);
}

export function UpdateStock(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateStock'](arg1, arg2, arg3, arg4);
}
