// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function DeleteMed(arg1) {
  return window['go']['main']['App']['DeleteMed'](arg1);
}

export function GetMedications() {
  return window['go']['main']['App']['GetMedications']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function Load() {
  return window['go']['main']['App']['Load']();
}

export function MarkUnsaved(arg1) {
  return window['go']['main']['App']['MarkUnsaved'](arg1);
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function SetUser(arg1) {
  return window['go']['main']['App']['SetUser'](arg1);
}

export function UpdateStock(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStock'](arg1, arg2, arg3);
}
