// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddUser(arg1:string):Promise<void>;

export function GetUser():Promise<string>;

export function GetUsers():Promise<Array<string>>;

export function Load():Promise<void>;

export function Medications():Promise<Array<main.Medication>>;

export function Save(arg1:Array<main.Medication>,arg2:string):Promise<void>;

export function SetUser(arg1:string):Promise<void>;

export function UpdateStock(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;
